name: Bluesky Auto Reposter (Beautygroup)

on:
  schedule:
    - cron: "0 */2 * * *"  # elke 2 uur
  workflow_dispatch:        # handmatig starten mogelijk

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install atproto

      - name: Run autoposter (beautygroup)
        env:
          BSKY_USERNAME_BG: ${{ secrets.BSKY_USERNAME_BG }}
          BSKY_PASSWORD_BG: ${{ secrets.BSKY_PASSWORD_BG }}
        run: python autoposter_bg.py
